apiVersion: v1
kind: ConfigMap
metadata:
  name: httpd-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Aplicación ArgoCD de prueba</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          margin: 40px;
          color: #333;
        }
        h1 {
          color: #2a6496;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
          background-color: #f9f9f9;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Bienvenido a la aplicación de ArgoCD</h1>
        <p>Este es un servidor Apache httpd desplegado a través de ArgoCD.</p>
        <p>La GitOps funciona correctamente.</p>
      </div>
    </body>
    </html>
