apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yonierpro-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YonierGomez/mcp-argocd-test.git
    targetRevision: HEAD
    path: nginx-yonier/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: yonierpro-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # No automated sync - manual sync only