apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Aplicación Nginx en ArgoCD - Namespace Demo</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          line-height: 1.6;
          margin: 40px;
          color: #333;
          background-color: #f4f4f4;
        }
        h1 {
          color: #0b5ed7;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
          padding: 20px;
          border: 1px solid #ddd;
          border-radius: 5px;
          background-color: #ffffff;
          box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .badge {
          background-color: #6c757d;
          color: white;
          padding: 5px 10px;
          border-radius: 4px;
          font-weight: bold;
        }
        .badge-info {
          background-color: #0dcaf0;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>Bienvenido a la aplicación Nginx</h1>
        <p>Este es un servidor Nginx desplegado a través de ArgoCD en el namespace <span class="badge badge-info">demo</span>.</p>
        <p>La implementación GitOps con ArgoCD funciona correctamente.</p>
      </div>
    </body>
    </html>
